# Restaurant-Table-Booking-
CREATE TABLE Customers1 (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    phone VARCHAR2(15),
    email VARCHAR2(100)
)
CREATE TABLE Tables (
    table_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_number NUMBER UNIQUE,
    capacity NUMBER
)
CREATE TABLE Bookings (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER,
    table_id NUMBER,
    booking_date DATE,
    booking_time VARCHAR2(10),
    number_of_people NUMBER,
    status VARCHAR2(20) DEFAULT 'Booked',
    CONSTRAINT fk_customer1
        FOREIGN KEY (customer_id)
        REFERENCES Customers1(customer_id),
    CONSTRAINT fk_table
        FOREIGN KEY (table_id)
        REFERENCES Tables(table_id)
)
INSERT INTO Customers1 (name, phone, email) VALUES 
('Alice Johnson', '9876543210', 'alice@example.com')INSERT INTO Customers1 (name, phone, email) VALUES 
('Bob Smith', '9123456780', 'bob@example.com');
INSERT INTO Tables (table_number, capacity) VALUES (4, 2);
INSERT INTO Tables (table_number, capacity) VALUES (5, 4);
INSERT INTO Tables (table_number, capacity) VALUES (6, 6);
SELECT 
    b.booking_id,
    c.name AS customer_name,
    t.table_number,
    b.booking_date,
    b.booking_time,
    b.number_of_people,
    b.status
FROM Bookings b
JOIN Customers1 c ON b.customer_id = c.customer_id
JOIN Tables t ON b.table_id = t.table_id;
